# Generated by Django 3.0.5 on 2020-05-10 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_auto_20180130_0904'),
        ('users', '0004_userprofile_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='referral',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='referrals.Referral'),
        ),
    ]
