# Generated by Django 2.2 on 2020-05-16 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200510_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_affiliate', to=settings.AUTH_USER_MODEL),
        ),
    ]
