# Generated by Django 2.2 on 2020-05-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200517_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='affamount',
            field=models.IntegerField(default=0),
        ),
    ]
