# Generated by Django 3.0.5 on 2020-05-05 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20160502_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Chapter'),
        ),
        migrations.AlterField(
            model_name='ytlink',
            name='yt_link_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Chapter'),
        ),
    ]
