# Generated by Django 3.0.5 on 2020-05-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_remove_course_purchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
    ]
