# Generated by Django 3.0.5 on 2020-05-05 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_remove_course_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='students1',
            new_name='students',
        ),
    ]
