# Generated by Django 3.0.5 on 2020-05-05 16:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0021_auto_20200505_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='students_to_course', through='courses.subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
