# Generated by Django 2.2 on 2020-05-16 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_auto_20200505_2143'),
    ]

    operations = [
       
        
        migrations.AddField(
            model_name='course',
            name='link',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='text',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='textblock',
            name='text_block_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Chapter'),
        ),
        
    ]
