# Generated by Django 3.0.5 on 2020-05-08 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_remove_subscriptions_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='purchased',
        ),
    ]
