# Generated by Django 3.0.5 on 2020-05-08 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_remove_course_purchased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textblock',
            name='text_block_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Chapter'),
        ),
        migrations.CreateModel(
            name='gdlink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('gd_link_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Chapter')),
            ],
        ),
    ]
